### ISSUE TITLE
ActionView::Template::Error ( isn't precompiled):

### ISSUE THREAD

**Issue by blackfoxdeveloper** [ejholmes/active_admin_editor#23]
Started GET "/admin/posts/new" for 87.245.186.102 at 2013-02-20 13:11:52 +0000
Processing by Admin::PostsController#new as HTML
  Rendered /home/shaelf/www/**********/shared/bundle/ruby/1.9.1/gems/activeadmin-0.5.1/app/views/active_admin/resource/new.html.arb (593.5ms)
Completed 500 Internal Server Error in 951ms

ActionView::Template::Error ( isn't precompiled):
    1: insert_tag renderer_for(:new)
  app/admin/posts.rb:14:in `block (4 levels) in <top (required)>'
  app/admin/posts.rb:13:in`block (3 levels) in <top (required)>'
  app/admin/posts.rb:12:in `block (2 levels) in <top (required)>'

``` ruby
ActiveAdmin.register Post do
  form do |f|
    f.inputs "Main" do
      f.input :title
      f.input :category
      f.input :lid, as: :html_editor
      f.input :text, as: :html_editor
      f.input :slug
    end
  end
end
```

**Comment by ejholmes** [comment]
Unless you have a reason for using 0.5.1. I'd recommend upgrading to the latest version (1.0.6), where this is fixed.

If you need to use 0.5.1, you should be able to fix this by adding the following to your `config/environments/production.rb`:

``` ruby
config.assets.precompile += [
  'active_admin/editor.css',
  'active_admin/editor/wysiwyg.css',
  'active_admin/editor.js'
]
```

**Comment by blackfoxdeveloper** [comment]
I'am use last version (Using active_admin_editor (1.0.6) from https://github.com/ejholmes/active_admin_editor.git (at master)).
Adding to the configuration does not work.
