### ISSUE TITLE
Parser rules not being applied?

### ISSUE THREAD

**Issue by alainus** [ejholmes/active_admin_editor#29]
I'm trying to customize the buttons on the ribbon. According to the documentation, I've set up on initializers/active_admin_editor.rb just to test it:

``` ruby
ActiveAdmin::Editor.configure do |config|

  config.parser_rules['tags']['h1'] = {
    'remove' => 1
  }
  config.parser_rules['tags']['h2'] = {
    'remove' => 1
  }
  config.parser_rules['tags']['h3'] = {
    'remove' => 1
  }  
end
```

But no avail. I did

``` ruby
rm -rf tmp/cache
```

As suggested on the docs and I restarted the server several times, but still the change makes no effect, and the h1, h2, h3 buttons are still showing up. What could be the problem?

**Comment by ejholmes** [comment]
Parser rules are actually different than what you're trying to do. Parser rules determine what tags are actually allowed in the markup itself (it doesn't have any effect on the buttons).

You should be able to just override [this template](https://github.com/ejholmes/active_admin_editor/blob/master/app/assets/javascripts/active_admin/editor/templates/toolbar.jst.ejs) in your app.

**Comment by alainus** [comment]
Excellent. I thought so. Thanks for the quick reply.

**Comment by patrickdavey** [comment]
Hi,

Probably a noob question :)  , but, can you please give instructions on how to override the template.  I have copied the template into the app/assets/..../templates directory but it is not overridden.  I'm assuming it needs to be required somewhere?

Thanks,
Patrick
