### ISSUE TITLE
Not working for nested objects

### ISSUE THREAD

**Issue by roughneck** [ejholmes/active_admin_editor#30]
Hey,

I'm using your great gem but unfortunately it doesn't seem to work for new nested objects.

This is how I use it in the config file /app/admin/issues.rb:
ActiveAdmin.register Issue do
  ...
  form do |f|
    ...
    f.has_many :topics do |t_f|
      ...
      t_f.input :text, as: :html_editor
      ...
    end
    f.actions
  end
end 

Now, when I click "New Topic", the form appears but text is just a simple textarea. After saving and clicking on edit, the topic and the input text is loaded correctly. I think the JS and whatnot is not correctly loaded because the form is appended after DOM is loaded?

**Comment by ejholmes** [comment]
You should be able to get around this by adding some hooks to your js that initializes the html editor:

``` javascript
$('.html_editor').editor(window.AA.editor_config)
```

**Comment by roughneck** [comment]
Hey,

Thanks for the quick reply. I added it to active_admin.js but doesn't seem to have any effect. Wrong file?

**Comment by ejholmes** [comment]
You're adding DOM elements dynamically. You need to attach the editor to
these elements once they've been created. The above code is what you need
to run to attach the editor, but you'll need to make sure it gets called
after the DOM elements are created.

**Comment by razielgn** [comment]
When I re-run

``` javascript
$('.html_editor').editor(window.AA.editor_config)
```

it breaks somewhere in JQuery UI's `$.widget.bridge`: https://github.com/jquery/jquery-ui/blob/1-10-stable/ui/jquery.ui.widget.js#L200.

It tries to call the method `option` on an instance of `Editor`, but there isn't.
Also, JQuery UI 1.10.x expects an object responding to `_init`, returned by `option`, while JQuery UI master just expects `option` on the instance.

Hope I was clear.

/cc @ingo86

**Comment by ryanwanger** [comment]
I'm struggling with this too. After the page loads, if I type `$('.html_editor').editor(window.AA.editor_config)` into the console, I get `TypeError: instance.option is not a function`

Individually, `window.AA.editor_config` returns an object and `$('.html_editor').editor` returns a function.
