### ISSUE TITLE
Heroku and image uploading

### ISSUE THREAD

**Issue by wullaski** [ejholmes/active_admin_editor#36]
The image upload button is not showing up on heroku but it is locally. I followed the heroku specific instructions on the doc and s3 is setup and working locally.

**Comment by wullaski** [comment]
I fixed it by changing a line in the application.rb file to

```
config.assets.initialize_on_precompile = true
```

**Comment by ejholmes** [comment]
Awesome! There's some notes on Heroku in the README that tells you to do
this, but I just noticed there's a typo.
