### ISSUE TITLE
Generator Fails without ActiveRecord

### ISSUE THREAD

**Issue by rajington** [ejholmes/active_admin_editor#4]
`rails g active_admin:editor` produces:

...`active_record/connection_adapters/abstract/connection_pool.rb:404:in `retrieve_connection': ActiveRecord::ConnectionNotEstablished (ActiveRecord::ConnectionNotEstablished)`

because it somehow relies on active record even though it just moves a css file

many projects may stop including active record when using mongoid or alternatives

**Comment by ejholmes** [comment]
Closing as old
