### ISSUE TITLE
embedding video

### ISSUE THREAD

**Issue by nurettin** [ejholmes/active_admin_editor#43]
Hi, I notice that pasting iframes for embedded videos doesn't work in source mode. 
However this is active_admin, not a forum. We should be able to embed videos in our website news. So it makes sense in the original editor, but we have to override this behavior in active_admin_editor.

**Comment by nurettin** [comment]
I see now that I can override parser rules in initializer

https://github.com/ejholmes/active_admin_editor/blob/master/app/assets/javascripts/active_admin/editor/config.js.erb

**Comment by dankmitchell** [comment]
I have an issue with embedding iframes, I have added the following parser which almost works, it allows the iframe tag but removes all the content inside -

ActiveAdmin.setup do |config|
  config.editor.parser_rules['tags']['iframe'] = {
  'remove' => 0
  }
end

**Comment by SerKnight** [comment]
I can't seem to find the solution to this iframe embedding problem.

ActiveAdmin::Editor.configure do |config|
  config.parser_rules['tags']['iframe'] = {
    'remove' => 0,
    check_attributes: {
      src: 'url',
      width: 'numbers',
      height: 'numbers'
    }
  }
end

with this it lets me post the height and width but for example posting this iframe

< iframe width="1280" height="720" src="//www.youtube-nocookie.com/embed/nhi-jyn748c?list=UUalUnzdQKDVpFWyFOXFsK6A" frameborder="0" allowfullscreen></iframe>

yields

< iframe width="1280" height="720">www.youtube-nocookie.com/embed/nhi-jyn748c?list=UUalUnzdQKDVpFWyFOXFsK6A&amp;lt;/a&amp;gt;" frameborder="0" allowfullscreen&amp;gt;</iframe>

Anyone have any solution for iframes and active_admin editor. If I come up with something I will post back.

**Comment by Joeyjoejoe** [comment]
The problem comes from the url of embeding videos who looks like this: //www.youtube.com/embed/id
Note the // at the begining. According to the wysihtml5 doc, this is not a valid url format for the parser_rules:

> check_attributes: checks the given HTML attribute via the given method
> - url: allows only valid urls (starting with http:// or https://)
> - src: allows something like "/foobar.jpg", "http://google.com", ...
> - href: allows something like "mailto:bert@foo.com", "http://google.com", "/foobar.jpg"
> - alt: strips unwanted characters. if the attribute is not set, then it gets set (to ensure valid and compatible HTML)
> - numbers: ensures that the attribute only contains numeric characters

But it seems solve on the main wysihtml5 project: https://github.com/xing/wysihtml5/issues/478
Maybe a little update could solve it on active_admin_editor (if it's still maintained, if not, a notice on the wiki would be great ;) ).
