### ISSUE TITLE
Image uploading won't work

### ISSUE THREAD

**Issue by reaktivo** [ejholmes/active_admin_editor#5]
I thought I configured active_admin_editor correctly, but when I click the Image upload button, nothing happens. I looked at the network inspector and I can see a `GET http://localhost:3000/admin/image_assets.json` with a 500 response code every time I click on it.

I'm currently on Rails 3.2.8 with Active Admin 0.4.4

**Comment by ejholmes** [comment]
If it's returning a 500 error then there's probably an exception being thrown. What do you see in the rails console?

**Comment by reaktivo** [comment]
Kinda strange, I already did a `rake db:migrate` but it won't create a assets table.

```
AdminUser Load (0.3ms)  SELECT "admin_users".* FROM "admin_users" WHERE "admin_users"."id" = 1 LIMIT 1
Completed 500 Internal Server Error in 2ms

ActiveRecord::StatementInvalid (Could not find table 'assets')
```

**Comment by ejholmes** [comment]
Did you run `rake active_admin_editor:install:migrations` to copy over the migrations? This should probably be in the readme....

**Comment by reaktivo** [comment]
Thank you, it works now. This should definitely be in the readme.
